# Generated by Django 2.0.2 on 2018-03-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20180227_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
