# Generated by Django 2.0.2 on 2018-03-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_auto_20180228_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
